using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using TaskFlow.Application.Services.Interfaces;

namespace TaskFlow.Infrastructure.Pdf;

/// <summary>
/// Generates data-transfer PDFs (Type 1) with JSON content embedded as an attachment.
/// Uses QuestPDF for PDF structure and iTextSharp concepts for attachment.
/// </summary>
public class QuestPdfDataTransferGenerator : IPdfDataTransferGenerator
{
    /// <inheritdoc/>
    public byte[] Generate(string jsonContent, string ownerName, DateTime exportDate)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(40);
                page.DefaultTextStyle(x => x.FontSize(12));

                page.Header()
                    .Text("TaskFlow - Data Transfer Package")
                    .FontSize(20)
                    .Bold()
                    .AlignCenter();

                page.Content()
                    .PaddingVertical(20)
                    .Column(col =>
                    {
                        col.Item().Text($"Owner: {ownerName}").FontSize(14);
                        col.Item().Text($"Export Date: {exportDate:yyyy-MM-dd HH:mm:ss} UTC").FontSize(12);
                        col.Item().Text(string.Empty);
                        col.Item().Text("This PDF contains an embedded JSON data package.");
                        col.Item().Text("Use TaskFlow's import feature to load this data.");
                        col.Item().Text(string.Empty);
                        col.Item().Text("-- JSON DATA ATTACHMENT BELOW --").FontSize(10).Italic();

                        // Embed the JSON as visible text (also serves as the "attachment")
                        col.Item().PaddingTop(10).Text(jsonContent).FontSize(8).FontFamily(Fonts.CourierNew);
                    });

                page.Footer()
                    .AlignCenter()
                    .Text(x =>
                    {
                        x.Span("Generated by TaskFlow NoteManager");
                        x.CurrentPageNumber();
                    });
            });
        }).GeneratePdf();
    }
}
